### ISSUE TITLE
cf push fails with "negative offset"

### ISSUE THREAD

**Issue by IonCaza** [springernature/cf-sonarqube-buildpack#1]
I'm following the directions in readme, attempting to use this buildpack in my PCF environment. When I `cf push` I get the following error:

> Getting app info...
readat /path_to/git/cf-sonarqube-buildpack/sonar.properties: negative offset
FAILED

Any ideas as to why this is happening?

**Comment by IonCaza** [comment]
This is the contents of `sonar.properties`

```
# Required metadata
sonar.projectKey=com.spacex
sonar.projectName=SpaceX
sonar.projectVersion=1.0
#sonar.jacoco.reportPath=build/jacoco/test.exec

# Comma-separated paths to directories with sources (required)
sonar.sources=.
sonar.exclusions=node_modules,deploy,**/src/test/java/**/*,**/**/src/test/java/**/*
sonar.test.inclusions=**/src/test/java/**/*,**/**/src/test/java/**/*
sonar.java.binaries=build/classes/**/*

# Language
sonar.language=java

# Encoding of the source files
sonar.sourceEncoding=UTF-8
```

**Comment by lumuell** [comment]
Hi @IonCaza 

is this still an open topic? Do you have the issue on a local deployment?

The buildpack is rather stupid and does nothing special with the `sonar.properties` file.

**Comment by IonCaza** [comment]
Pretty sure I ended up scrubbing this whole thing. Didn't work properly.
